### ISSUE TITLE
发布新的主题 Please post on offical site

### ISSUE THREAD

**Issue by tsuibin** [typcn/LeanClub#12]
f12调式

/api/post/new

返回 
Please post on offical site

**Comment by tsuibin** [comment]
源码main.cpp第380行 
380         if(Referer.find("https://leanclub.org/post/new") == std::string::npos){

**Comment by tsuibin** [comment]
先简单的注释掉该代码段即可

**Comment by typcn** [comment]
我已经修复了这个问题，从 master pull 一下即可，会自动识别 config 里面的域名

**Comment by tsuibin** [comment]
ok
