### ISSUE TITLE
附件上传后无法显示

### ISSUE THREAD

**Issue by tsuibin** [typcn/LeanClub#13]
帖子内显示为：
[2015-12-15 14-41-53屏幕截图.png](/attachments/8225FBF27323636DF6F2933C6B7DA8F44BB810A0/1450174234SISV7O.png)
无法看到图片

**Comment by typcn** [comment]
需要配置 nginx，见首页

**Comment by tsuibin** [comment]
在运行目录下创建 attachments 目录后解决

**Comment by tsuibin** [comment]
不对，奇怪，刚刚发布的可以显示出来，但是attachments目录下并没有文件

刷新后，就不可见了

**Comment by typcn** [comment]
浏览器抓个包看看

**Comment by tsuibin** [comment]
不知道存哪去了

但是这里可以打开
http://o2ee.picp.net/attachments/8225FBF27323636DF6F2933C6B7DA8F44BB810A0/1450175981WB50IS.png

Request URL:http://o2ee.picp.net/api/file/simpleUpload
Request Method:POST
Status Code:200 OK
Remote Address:103.44.145.245:80
Response Headers
view source
Connection:keep-alive
Content-Length:61
Date:Tue, 15 Dec 2015 10:39:41 GMT
Server:nginx/1.9.2
X-Frame-Options:DENY
X-XSS-Protection:1; mode=block
Request Headers
view source
Accept:application/json
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Content-Length:134634
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryWA6Md9pLwKmJWMz8
Cookie:LBSESSIONID=JZDYGLG4XBJMEXNF6Y7EAHXR553SVLGGXJDT9J10; _ga=GA1.2.896167595.1450095965
Host:o2ee.picp.net
Origin:http://o2ee.picp.net
Referer:http://o2ee.picp.net/topic/dfa48533fec46d565e079a46b20349d6
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.8 Safari/537.36
X-Requested-With:XMLHttpRequest
Request Payload
------WebKitFormBoundaryWA6Md9pLwKmJWMz8
Content-Disposition: form-data; name="file"; filename="2015-12-15 14-41-53屏幕截图.png"
Content-Type: image/png

------WebKitFormBoundaryWA6Md9pLwKmJWMz8--

**Comment by typcn** [comment]
find 命令找一下 1450175981WB50IS.png

**Comment by tsuibin** [comment]
找到了，在nginx 设置的root下创建了attachments目录，文件都在这个下面

**Comment by tsuibin** [comment]
不知为何，帖子里面不能把字符串转换成对应的图片
asdfasdfsadfsdaf [2015-12-15 14-41-53屏幕截图.png](/attachments/8225FBF27323636DF6F2933C6B7DA8F44BB810A0/1450175126NBUVH2.png) [2015-12-15 14-41-53屏幕截图.png](/attachments/8225FBF27323636DF6F2933C6B7DA8F44BB810A0/1450175220J9UW7M.png)

**Comment by typcn** [comment]
em.. MarkDown 解析器为了防止 javascript 注入的一个小问题，可以让链接以 //  开头，or wait for fix

**Comment by tsuibin** [comment]
./utils.cpp:            if(!createFolder("../attachments/" + uid)) return "create folder failed";
./utils.cpp:            std::ofstream ofile("../attachments/" + uid + "/" + filename, std::ios::binary);

**Comment by tsuibin** [comment]
双斜线 // 就变成了一个 link了
也没有把图片显示出来
<a href=xxx> asdfasdf</a>

**Comment by tsuibin** [comment]
```
<a target="_blank" href="//attachments/8225FBF27323636DF6F2933C6B7DA8F44BB810A0/1450175981WB50IS.png">2015-12-15 14-41-53屏幕截图.png</a>
```

**Comment by typcn** [comment]
em.. 搞错了 等我更新下 markdown 解析器

**Comment by typcn** [comment]
Fixed in https://github.com/typcn/LeanClub/commit/c5b1a4e970f8e9d6f48f399e6d5ae6d1d6d24498
