### ISSUE TITLE
config.h中   DATABASE_USERNAME 和 DATABASE_PASSWORD如何配置?

### ISSUE THREAD

**Issue by tsuibin** [typcn/LeanClub#7]
const std::string DATABASE_USERNAME = "";
const std::string DATABASE_PASSWORD = "";
# GITHUB APP OAUTH

const std::string GITHUB_OAUTH_ID = "";
const std::string GITHUB_OAUTH_SECRET = "";
# GOOGLE APP OAUTH

const std::string GOOGLE_OAUTH_ID = "";
const std::string GOOGLE_OAUTH_SECRET = "";
# Twitter OAUTH

const std::string Twitter_OAUTH_ID = "";
const std::string Twitter_OAUTH_SECRET = "";

**Comment by tsuibin** [comment]
登陆数据库管理界面
例如:
http://10.0.0.49:5984/_utils/index.html
找到右下角
Welcome to Admin Party! 
Everyone is admin. Fix this

点击
Fix this
在Create Server Admin 对话框中填写你要设置的用户名和密码
比如
username: root
password:a12345
然后修改
src/config.h 中
const std::string DATABASE_USERNAME = "";
const std::string DATABASE_PASSWORD = "";
为
const std::string DATABASE_USERNAME = "root";
const std::string DATABASE_PASSWORD = "a12345";

**Comment by tsuibin** [comment]
然后执行make 
生成可执行文件leanclub
运行leanclub

**Comment by tsuibin** [comment]
but........

./leanclub 
Fatal Error: Unable to get category,is database down?

**Comment by typcn** [comment]
导入那些默认的json文件

**Comment by tsuibin** [comment]
数据都导入了

“
"1"
ID: 1
{rev: "1-142983e97e9ae13c440dea85b69308a0"}
"10"
ID: 10
{rev: "1-b885c80accfdecd0343a5d03c5ad8ebf"}
"11"
ID: 11
{rev: "1-10012bb7893ea6beeae7219cac85a3ae"}
"12"
ID: 12
{rev: "1-6445f1d0d68672f21bc040e8870352d2"}
"13"
ID: 13
{rev: "1-8d0f6bf70144a554a5f731774443bdaf"}
"14"
ID: 14
{rev: "1-f1cbc517af2a0148a551ac95efffc1b9"}
"15"
ID: 15
{rev: "1-ce20eabaa739add8054111c9ff119a0f"}
"16"
ID: 16
{rev: "1-9c871dc5058e5b16dfa3af840859b763"}
"17"
ID: 17
{rev: "1-7ffaa3a317ad532bceaf18abcb5551f6"}
"2"
ID: 2
{rev: "1-a7040fd1a6754a1cd7b0fec1fd6511bf"}
”

**Comment by tsuibin** [comment]
#define DATABASE_URL "http://127.0.0.1:5984"
#define REDIS_MASTER_IP "127.0.0.1"

DATABASE_URL 这个是填写 http://127.0.0.1:5984
还是 http://127.0.0.1 ?

**Comment by typcn** [comment]
http 开头 / 结尾

**Comment by tsuibin** [comment]
tsuibin@compiler01:~/src/LeanClub/build$ ./leanclub 
APP Listening on port 18080 with 500 thread(s)
运行起来了
DATABASE_URL结尾掉了个/
