### ISSUE TITLE
 [ERROR   ] An uncaught exception occurred: invalid json object

### ISSUE THREAD

**Issue by tsuibin** [typcn/LeanClub#8]
wget -c http://localhost:18080/
--2015-12-11 10:02:17--  http://localhost:18080/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:18080... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:18080... connected.
HTTP request sent, awaiting response... (2015-12-11 02:02:17) [ERROR   ] An uncaught exception occurred: invalid json object
500 Internal Server Error

看样子是数据库有点问题

**Comment by typcn** [comment]
啊，我的JSON可能少了点东西，在 topics 里面添加一个帖子

```
{
  "updateAt": 0,
  "content": [
    "帖子内容"
  ],
  "status": 1,
  "category": "分类ID，填入1即可",
  "createAt": 1430910337,
  "title": "帖子标题",
  "lastReply": 1431000451,
  "user": "typcn",
  "replies": []
}
```

**Comment by tsuibin** [comment]
添加了一条新记录

{
   "_id": "dfa48533fec46d565e079a46b203372a",
   "_rev": "1-81f3679d61cb28eebb7ebd7acf0c25ba",
   "updateAt": 0,
   "content": [
       "帖子内容"
   ],
   "status": 1,
   "category": "1",
   "createAt": 1430910337,
   "title": "帖子标题",
   "lastReply": 1431000451,
   "user": "typcn",
   "replies": [
   ]
}

首页可以访问了
